import type { Email } from '@/types/Email'

export const mockEmails: Email[] = [
  {
    id: '3',
    title: 'Bienvenida a la plataforma',
    subject: '¡Nos alegra tenerte aquí!',
    body: 'Gracias por registrarte. Empecemos esta aventura juntos.',
    filesIds: [],
    mode: 'unique',
    days: null,
    sendingDay: new Date('2025-04-10'),
    sendingHour: '09:00',
    addresseeMode: 'all',
    addresseeEmails: null,
    addresseePercent: null,
    createdAt: new Date('2025-04-01T08:00:00'),
  },
  {
    id: '1',
    title: 'Tips de productividad',
    subject: 'Consejos para comenzar la semana con todo',
    body: 'Organiza tu semana con estos simples pasos...',
    filesIds: ['file_prod_001'],
    mode: 'some-days',
    days: ['monday'],
    sendingDay: null,
    sendingHour: '08:30',
    addresseeMode: 'percent',
    addresseeEmails: null,
    addresseePercent: 50,
    createdAt: new Date('2025-03-28T09:15:00'),
  },
  {
    id: '86',
    title: 'Newsletter diario',
    subject: 'Resumen de noticias y actualizaciones',
    body: 'Te compartimos lo más importante del día.',
    filesIds: [],
    mode: 'daily',
    days: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    sendingDay: null,
    sendingHour: '07:00',
    addresseeMode: 'all',
    addresseeEmails: null,
    addresseePercent: null,
    createdAt: new Date('2025-03-27T07:00:00'),
  },
  {
    id: '33',
    title: 'Invitación al webinar',
    subject: '¡Participa este jueves!',
    body: 'No te pierdas nuestro webinar sobre productividad digital.',
    filesIds: ['webinar_invite_001'],
    mode: 'some-days',
    days: ['thursday'],
    sendingDay: null,
    sendingHour: '17:00',
    addresseeMode: 'some',
    addresseeEmails: ['maria@example.com', 'luis@example.com'],
    addresseePercent: null,
    createdAt: new Date('2025-03-30T14:00:00'),
  },
  {
    id: '62',
    title: 'Encuesta de satisfacción',
    subject: 'Tu opinión nos ayuda a mejorar',
    body: 'Por favor, completa esta encuesta de 2 minutos.',
    filesIds: ['survey_form_001'],
    mode: 'unique',
    days: null,
    sendingDay: new Date('2025-04-15'),
    sendingHour: '12:00',
    addresseeMode: 'percent',
    addresseeEmails: null,
    addresseePercent: 25,
    createdAt: new Date('2025-04-03T13:30:00'),
  },
  {
    id: '56',
    title: 'Actualizaciones del producto',
    subject: 'Nuevas funcionalidades disponibles',
    body: 'Descubre las mejoras que acabamos de lanzar.',
    filesIds: ['changelog_001'],
    mode: 'unique',
    days: null,
    sendingDay: new Date('2025-04-20'),
    sendingHour: '16:45',
    addresseeMode: 'all',
    addresseeEmails: null,
    addresseePercent: null,
    createdAt: new Date('2025-04-05T14:45:00'),
  },
  {
    id: '98',
    title: 'Tips semanales de eficiencia',
    subject: 'Mejora tu workflow con estos tips',
    body: 'Aplicando estos hábitos verás un gran cambio.',
    filesIds: [],
    mode: 'some-days',
    days: ['wednesday'],
    sendingDay: null,
    sendingHour: '09:15',
    addresseeMode: 'all',
    addresseeEmails: null,
    addresseePercent: null,
    createdAt: new Date('2025-04-01T09:00:00'),
  },
  {
    id: '18',
    title: 'Cierre de campaña',
    subject: 'Último día para aprovechar la oferta',
    body: 'No dejes pasar esta oportunidad única.',
    filesIds: ['promo_final_001'],
    mode: 'unique',
    days: null,
    sendingDay: new Date('2025-04-25'),
    sendingHour: '19:00',
    addresseeMode: 'some',
    addresseeEmails: ['ana@example.com'],
    addresseePercent: null,
    createdAt: new Date('2025-04-06T16:00:00'),
  },
]
